Replace `npm` dependency with `exec`
The current search functionality is disabled because the NPM API no longer supports the search call.

For newer NPM versions the entire programmatic API has been removed from NPM.

```
~/C/G/kosmtik (eslint-8|✚2) 🠞 node index.js plugins --install kosmtik-map-compare
/home/hidde/Code/Git/kosmtik/node_modules/npm/index.js:4
  throw new Error('The programmatic API was removed in npm v8.0.0')
  ^

Error: The programmatic API was removed in npm v8.0.0
    at Object.<anonymous> (/home/hidde/Code/Git/kosmtik/node_modules/npm/index.js:4:9)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/home/hidde/Code/Git/kosmtik/src/back/PluginsManager.js:1:11)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
```

In addition the `npm` dependency is huge, and generates half of the size of the `package-lock.json` (which is not committed).

With this PR:
```
$ node ./index.js plugins --available

[Core] Loading config from /home/hidde/.config/kosmtik.yml
[Core] Loading plugin from ../plugins/base-exporters/index.js
[Core] Loading plugin from ../plugins/hash/index.js
[Core] Loading plugin from ../plugins/local-config/index.js
[Core] Loading plugin from ../plugins/datasource-loader/index.js
[Core] Loading plugin from ../plugins/version/index.js
[Core] Loading plugin from kosmtik-map-compare
[Core] Loading plugin from kosmtik-fetch-remote
Loading available plugins…
.  kosmtik-overlay (Add an overlay to Kosmtik)
.  kosmtik-osm-data-overlay (Display an interactive OSM data overlay in Kosmtik)
.  kosmtik-overpass-layer (Add overpass layers to your Kosmetik project)
.  kosmtik-tiles-export (Export tiles tree from your Kosmtik project)
.  kosmtik-open-in-josm (Add a control to open JOSM with current map view)
.  kosmtik-deploy (Deploy your local Kosmtik project on a remote server)
✓  kosmtik-map-compare (Add a map to compare side-by-side with your work)
.  kosmtik-mapnik-reference (Browse Mapnik and CartoCSS reference in Kosmtik)
.  kosmtik-magnacarto (Kosmtik plugin to support Magnacarto renderer)
✓  kosmtik-fetch-remote (Kosmtik plugin to fetch remote layer data)
.  kosmtik-place-search (Search for places in Kosmtik)
.  kosmtik-geojson-overlay (Show a geojson overlay on top of your Kosmtik map)
.  kosmtik-mbtiles-export (Export your Kosmtik project in MBTiles)
.  kosmtik-mbtiles-source (Use an MBTiles file as a source for a vector tile based probject in kosmtik)
```

And installation
```
$ node ./index.js plugins --install kosmtik-fetch-remote

[Core] Loading config from /home/hidde/.config/kosmtik.yml
[Core] Loading plugin from ../plugins/base-exporters/index.js
[Core] Loading plugin from ../plugins/hash/index.js
[Core] Loading plugin from ../plugins/local-config/index.js
[Core] Loading plugin from ../plugins/datasource-loader/index.js
[Core] Loading plugin from ../plugins/version/index.js
[Core] Loading plugin from kosmtik-map-compare
[Core] Starting installation of kosmtik-fetch-remote
[Core] Successfully installed package kosmtik-fetch-remote
[Core] Attached plugin: kosmtik-fetch-remote
[Core] Saved env conf to /home/hidde/.config/kosmtik.yml
```